name: tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.5
      id: go

    - name: Check out source
      uses: actions/checkout@v1

    - name: Install libgit2
      run: sudo ./scripts/install_libgit2.sh

    - name: Vet
      run: make vet
    
    - name: Test
      run: make test-cover
    
    - name: Upload coverage
      uses: codecov/codecov-action@v1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libgit2
        run: |
          git clone https://github.com/libgit2/libgit2.git ~/libgit2
          cd ~/libgit2
          git checkout v1.1.0
          mkdir build && cd build
          sudo cmake .. -DBUILD_CLAR=0
          sudo cmake --build . --target install

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --build-tags sqlite_vtable,static,system_libgit2
